---
name: Bug Report
about: Create a report to help us improve
title: "[Bug] "
labels: bug
assignees: ''
---

## Describe the bug
A clear and concise description of the bug.

## To Reproduce
Steps to reproduce the behavior:
1. …
2. …

## Expected behavior
What you expected to happen.

## Screenshots / Logs
If applicable, add screenshots or logs.

## Additional context
Anything else relevant.
