name: Feature request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!  
        Please provide as much detail as possible.

  - type: input
    id: summary
    attributes:
      label: Summary
      description: Short description of the feature.
      placeholder: ex. Add dark mode support
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Detailed description
      description: Explain the feature in detail and how it would work.
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why do you think this feature is needed? What problem does it solve?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: List any alternative solutions or features you've considered.

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
